### ISSUE TITLE
Update demo/test process to use PyPi instead of cloning aries-cloudagent-python

### ISSUE THREAD

**Issue by swcurran** [bcgov/aries-vcr-issuer-controller#16]
We'd like users to use released versions of `aries-cloudagent-python` - at least by default. In the current instructions, users are asked to clone and build that repo to get the agent code. Please update the primary instructions and add a dockerfile process to generate and run the agent using the PyPi package directly.

We might add instructions on how to use the issuer controller with the latest `aries-cloudagent-python` for agent developers that want to use the code in this repo for testing, but we definitely want that to be the weird case and discourage its use.

**Comment by esune** [comment]
WIP pull request for the container image: https://github.com/bcgov/aries-cloudagent-container/pull/4

**Comment by esune** [comment]
@ianco the issuer-controller agent uses the `tob-agent` image right now. Are we okay with it, or should I put together a small dockerfile that mimics what `tob-agent` does and resides in this repo? If theimage is the same (it is) I'd vote to just reference it and avoid having duplicate dockerfiles around - this repository has no real use if the credential registry is not running already.

**Comment by ianco** [comment]
@esune  since this controller can only talk to the indy cat credential registry, and it needs the register issuer protocol (which is in the indy cat repo) I vote we just use the same image.  If someone is running this repo then they need to first get the credential registry running, so they should have this image already.
